### PR TITLE
set alt clip to 0 if there is no other alt support

### PR DESCRIPTION
**Pull request by brentp**
when doing population calling, we're genotype thousands of samples at so allowing only soft clips (with no split support) to create a HET creates many false positives.

this sets the clip support to 0 unless there is other alt support. it also down-weights clip support because it's only support 1 end so it should have at most half the weight of other evidience.

### CODE REVIEW

**Comment by brentp** [comment]
discovered with @ryanlayer

**Comment by ernfrid** [comment]
I don't think we ever intended to use clips for discovery so that's a clear bug. Thanks for catching it.

For the down-weighting, I think it may already be addressed but sneakily.

Clips are created as fake splitters in the code where the other half of the splitter has mapping quality 0 and no chromosome. See: https://github.com/hall-lab/svtyper/blob/master/svtyper/parsers.py#L967-L971

The support is calculated here: https://github.com/hall-lab/svtyper/blob/master/svtyper/classic.py#L321

It's been a while, but I believe it's averaging the mapping quality of both split pieces and in the case where the mapping quality is very low and/or one half of the splitter doesn't support the breakpoint, the support is halved.

Does this address your concern with the downweighting @brentp? Or do you and @ryanlayer think it should be downweighted further? (Noting that your pull request divides by 3 it seems it might need to be).

**Comment by brentp** [comment]
I think it probably matters very little as long as you zero it out if there is no other support.

**Comment by ernfrid** [comment]
I think this should take care of it. Thanks again for bringing this to our attention and providing a fix.

**Comment by brentp** [comment]
thank you for the quick fix and new release.

**Pull request merged**
